### ISSUE TITLE
Should make the media selector more configurable?

### ISSUE THREAD

**Issue by zishon** [spider-rs/spider#104]
I'm using spider-rs to build a simple system which make a snapshot of my website, but it can't scrape the css/js/image.. and so on.
Will it be supported in future?

**Comment by j-mendez** [comment]
Hi @zishon, yes exposing the selector or gathering all assets that relate to the domain. Going to keep this issue open until the changes are made. Thank you

**Comment by j-mendez** [comment]
Released in `1.26.0` use the feature flag `full_resources` in order to enable.
