### ISSUE TITLE
[Feature request] URL Globbing

### ISSUE THREAD

**Issue by roniemartinez** [spider-rs/spider#111]
I would like to propose an implementation of `curl`'s URL globbing: https://everything.curl.dev/cmdline/globbing

Sure, this can be done via loop, but it is useful and easier to control if there is one URL to use to [Pause, Resume or Shutdown ](https://github.com/spider-rs/spider/blob/main/spider/README.md#pause-resume-and-shutdown) the spider

**Comment by j-mendez** [comment]
@roniemartinez this is a powerful feature. I think we can get the full scope of it done. It may take some incremental steps for each part. We can do subdomain and tld globing with the current setup with little changes.

**Comment by roniemartinez** [comment]
Yes, I agree with doing it incrementally. 💯

**Comment by j-mendez** [comment]
@roniemartinez do you know if this is a feature you would like to take initiative on?

**Comment by roniemartinez** [comment]
@j-mendez I started a draft in https://github.com/spider-rs/spider/pull/113 though I might need to break things in the `Website` (or you can integrate it)

**Comment by j-mendez** [comment]
@roniemartinez either or works, appreciate the heads up on the pr.
