### ISSUE TITLE
[Bug] Follows external website on redirect (302, 301, 3XX)

### ISSUE THREAD

**Issue by roniemartinez** [spider-rs/spider#119]
First of all kudos and thank you for fixing the bugs that I report @j-mendez 

It seems that the spider still follow redirects even when the domain is not same to the input domain.

#### Example: (not actual websites)

| Sequence | GET  | Response | Comment |
| ------------- | ------------- | ------------- | ------------- |
| 1 | https://example.com/redirect-to-another | 302 http://choosealicense.com  | Should have stopped here immediately |
| 2 | http://choosealicense.com  | 301 https://choosealicense.com | Outside of target domain |
| 3 | https://choosealicense.com  | 200 | Outside of target domain |

**Comment by roniemartinez** [comment]
I think this is related to `reqwest` redirect policy.
https://docs.rs/reqwest/latest/reqwest/redirect/struct.Policy.html

**Comment by j-mendez** [comment]
@roniemartinez fix deployed in `v1.30.3` https://github.com/spider-rs/spider/commits/main. Thank you!

**Comment by roniemartinez** [comment]
Thank you @j-mendez It works! 🚀
