### ISSUE TITLE
Blacklist regex for CLI does not seem to work

### ISSUE THREAD

**Issue by Byter09** [spider-rs/spider#129]
I've been trying to crawl a website and ignore paths like `/news` or whatever using `-b`, but nothing seems to work.

I looked at https://github.com/spider-rs/spider/pull/36 and from what I can see the feature `regex` is not enabled for the CLI part of this project.

Is this on purpose? I also can't seem to find any example or test that tests that the CLI can actually do this.

Hope I'm just blind and overlooking something.

Thanks for the tool! :D

**Comment by Byter09** [comment]
Here's a command to reproduce it:
spider -v -s -r  -D 10 -d https://choosealicense.com -b "bsd" download -t choosealicense

That's close to what I'm actually trying to crawl/scrape/download. As you can see, it still pulls the `bsd` license and everything

**Comment by j-mendez** [comment]
Hi @Byter09 thank you for the issue! The regex feature can be installed with `1.36.5`.

`cargo install spider_cli --features regex`.
