### ISSUE TITLE
Also extract urls that are pointing to  other domains? [CLI]

### ISSUE THREAD

**Issue by sebs** [spider-rs/spider#135]
I only get 'internal links'. 

Is there a way to get external links too?

**Comment by j-mendez** [comment]
Hi @sebs, not at the moment. It would be a nice feature to have. Some companies like Disney have their main domain as the root page, while having every link that they care about treated as a different dns name on the page. It makes it hard to gather all the website data with this pattern.

**Comment by j-mendez** [comment]
@sebs this is now available in 1.42.0.

![crawling multiple domains as one for the url https://rssea.fr and https://loto.rsseau.fr](https://github.com/spider-rs/spider/assets/8095978/3e7135ce-01c8-4cec-8f8f-a7fb5ccae44c)

Thank you for the issue!

**Comment by sebs** [comment]
ah i love this so much ;) you are solving a big problem for me. Trying to build a url dataset of 20 million for a coding challenge ;) 

I do really aprechiate this as it saves me a ton of time.

**Comment by j-mendez** [comment]
@sebs no worries at all, feel free to keep reporting issues even if it is just a simple question! This feature is something that I wanted for awhile too since this project is the main engine for collecting data.

**Comment by sebs** [comment]
i did not find the option for external domains in the cli version of spider. Maybe the change did not make it through?

**Comment by j-mendez** [comment]
@sebs at the moment not available in the CLI. Not all features go 1:1, if they fit the CLI they also need to be added separately. Going to re-open this issue for the CLI.

**Comment by j-mendez** [comment]
Now available in the CLI v1.45.10. Example below to group domains.

`spider --domain https://rsseau.fr -E  https://loto.rsseau.fr/  crawl -o`.

The `E` flag can also be written as `external-domains`.

**Comment by sebs** [comment]
maybe make it possible to add a * to extract all external domain links? 

Background: one thing I am using the tool for is to create link maps ... aka page a links to page b

**Comment by j-mendez** [comment]
@sebs done via `1.46.0`. Thank you!

**Comment by sebs** [comment]
<3

**Comment by apsaltis** [comment]
Hi,
Perhaps I'm using this incorrectly, but when I try the following command, using spider_cli 1.80.78:

spider -t -v --url https://www.theconsortium.cloud/  --depth 10 -s -E https://39834791.fs1.hubspotusercontent-na1.net/ scrape

I never see any URLs from the external domain, even though on one of the pages crawled https://www.theconsortium.cloud/application-consulting-services-page there is a button that links to a pdf on Hubspot, the HTML looks like this: 

<a class="hs-button " href="https://39834791.fs1.hubspotusercontent-na1.net/hubfs/39834791/Application%20Rationalization.pdf" id="hs-button_widget_1686407295591" target="_blank" rel="noopener ">
  Download our one-pager for more information
</a>

the output from the scape command looks like this for that page:
{
    "html": "",
    "links": [],
    "url": "https://www.theconsortium.cloud/application-consulting-services-page"
  },

Is there a way, either programmatically or via the CLI, to have a spider detect all of the links on a page? Thanks in advance.

**Comment by scientiac** [comment]
How do I extract the URLs pointing to other domains? using the crate not the cli.. Trying to make  a crawler with self discovery of new sites from one seed.

**Comment by j-mendez** [comment]
> How do I extract the URLs pointing to other domains? using the crate not the cli.. Trying to make  a crawler with self discovery of new sites from one seed.

Use website.external_domains to add domains into the group for discovery.

**Comment by scientiac** [comment]
I mean to catch all the websites that aren't under the same domain... not the oned i specify

**Comment by j-mendez** [comment]
> I mean to catch all the websites that aren't under the same domain... not the ones i specify... like using -E * , a catchall

Set website.external_domains to a wildcard. If this isn't a thing yet, I can add it in later.

**Comment by scientiac** [comment]
I don't think it is a thing.

**Comment by j-mendez** [comment]
> I don't think it is a thing.

![CASELESS_WILD_CARD external domains handling](https://github.com/spider-rs/spider/assets/8095978/2315505b-c75d-4e10-a9eb-f979df595fee)

https://github.com/spider-rs/spider/issues/135#issuecomment-1733947549 looks like it was done. Use `website.with_external_domains`.

**Comment by scientiac** [comment]
![image](https://github.com/spider-rs/spider/assets/58177655/888a0567-34c5-4e67-bd56-9f68fa26b190)

asks me to provide an argument

**Comment by j-mendez** [comment]
> ![image](https://private-user-images.githubusercontent.com/58177655/327128951-888a0567-34c5-4e67-bd56-9f68fa26b190.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NzA0MDcsIm5iZiI6MTcxNDU3MDEwNywicGF0aCI6Ii81ODE3NzY1NS8zMjcxMjg5NTEtODg4YTA1NjctMzRjNS00ZTY3LWJkNTYtOWY2OGZhMjZiMTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDEzMjgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNDYwYTY5MDcxMzUzOWM0ZjAxMzg1MmJlOGEwNmVlMmRmMmQ1YTE3YjBlMTg4NmRlZjI0N2Q2OGRiMWRhNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d3UCDNHdahvXULn91zNOhJz0GMwJOfRSYlXayV3KUNs)
> 
> asks me to provide an argument

Correct, follow the type for the function. Set the value to a wildcard. Not sure what IDE that is, rust-analyzer is almost a must when using any crate.

**Comment by scientiac** [comment]
I used this 

```
        .with_external_domains(Some(vec!["*"].into_iter().map(|s| s.to_string())))
```

this compiles just fine but doesn't give me any external link from the site

```
use spider::tokio;
use spider::website::Website;

#[tokio::main]
async fn main() {
    let mut website: Website = Website::new("https://carboxi.de");

    website.crawl().await;
    website.with_respect_robots_txt(true)
        .with_subdomains(true)
        .with_external_domains(Some(vec!["*"].into_iter().map(|s| s.to_string())));

    let links = website.get_links();
    let url = website.get_url().inner();
    let status = website.get_status();

    println!("URL: {:?}", url);
    println!("Status: {:?}\n", status);

    for link in links {
        println!("{:?}", link.as_ref());
    }
}
```

i dont think i understand what the wildcard for this is
