### ISSUE TITLE
`with_on_link_find_callback` doesn't exist

### ISSUE THREAD

**Issue by SamuelMarks** [spider-rs/spider#145]
As of 323d03f:

```sh
spider$ rg -F with_on_link_find_callback
spider/README.md
78:    .with_on_link_find_callback(Some(|link, html| {
```

Looks like it did exist at 9bc8888 in at https://github.com/spider-rs/spider/blob/9bc8888/spider/src/website.rs#L1136-L1148:
```rs
    /// Perform a callback to run on each link find.
    pub fn with_on_link_find_callback(
        &mut self,
        on_link_find_callback: Option<
            fn(CaseInsensitiveString, Option<String>) -> (CaseInsensitiveString, Option<String>),
        >,
    ) -> &mut Self {
        match on_link_find_callback {
            Some(callback) => self.on_link_find_callback = Some(callback.into()),
            _ => self.on_link_find_callback = None,
        };
        self
    }
```

Am I—and thus the README—missing an import; was this mistakenly removed; renamed; hidden behind a feature flag; or should it be removed from the README?

**Comment by j-mendez** [comment]
thanks for the issue, @SamuelMarks yes this needs to be removed fixed on [main](https://github.com/spider-rs/spider/commits/main).

**Comment by SamuelMarks** [comment]
That was fast! - Great.
