### ISSUE TITLE
Scraping timeout Issue

### ISSUE THREAD

**Issue by virajk31** [spider-rs/spider#158]
I am encountering an issue while scraping a list of websites (~400). I have implemented a timeout of 5 minutes for each entry, and if the crawling process takes longer, it should skip to the next website. However, sometimes execution gets stuck at some entry and does not proceed further, even after implementing the timeout.

code:
` async fn fetch_and_store(companies: Vec<Company>, output_file: &str,) -> Result<(), Box<dyn std::error::Error>> {

    let timeout_duration = Duration::from_secs(300);

    let result: Vec<CompanyInfo> = companies.par_iter().map(|company| {
        info!("crawling:: {}", company.website);
        let link_start_time = Instant::now();
        let rt = Runtime::new().unwrap();

        let website = rt.block_on(async {
            
            let mut website: Website = Website::new(&company.website);
            
            let mut headers = header::HeaderMap::new();
            headers.insert(
                header::USER_AGENT,
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
                    .parse()
                    .unwrap(),
            );

            website.with_headers(Some(headers));
            website.with_respect_robots_txt(true);
            // website.scrape().await;
            match timeout(timeout_duration, website.scrape()).await {
                Ok(_) => {
                    // success
                    info!("crawl completed:: {}", company.website)
                }
                Err(_) => {
                    info!("crawl timed out after {:?} seconds", timeout_duration);
                }
            }
            website
        });

        let links: Vec<CaseInsensitiveString> = website.get_links().iter().cloned().collect();
        let pages: Vec<PageWrapper> = website
            .get_pages()
            .map_or_else(|| Vec::<PageWrapper>::new(), |pages| pages.iter().map(|page| (page).into()).collect());

        let link_elapsed = link_start_time.elapsed();
        CompanyInfo {
            company: company.company.to_owned(),
            link: company.website.to_owned(),
            links,
            pages,
        }
    }).collect();

    info!("crawled all companies");

    let elapsed = start_time.elapsed();
    
    let json_result = serde_json::to_string_pretty(&result).unwrap();
    let mut output_file = File::create(output_file)?;
    output_file.write_all(json_result.as_bytes())?;

    info!("Results stored in {:?}", output_file);
    info!("Total time taken: {:?}", elapsed);

    Ok(())
}`

**Comment by j-mendez** [comment]
Closing unreproducible, testing with `tokio::time::timeout` the future cancels ex: 

```rs
    if let Err(_) = tokio::time::timeout(Duration::from_millis(2500),  website.crawl()).await {
        println!("did not receive value within 2500 ms");
    }
```
