### ISSUE TITLE
Extracting all urls on a page

### ISSUE THREAD

**Issue by apsaltis** [spider-rs/spider#160]
Hi,
This is related to issue [#135 ](https://github.com/spider-rs/spider/issues/135). Perhaps I'm using this incorrectly, but when I try the following command, using spider_cli 1.80.78:

spider -t -v --url https://www.theconsortium.cloud/ --depth 10 -s -E https://39834791.fs1.hubspotusercontent-na1.net/ scrape

I never see any URLs from the external domain, even though on one of the pages crawled https://www.theconsortium.cloud/application-consulting-services-page there is a button that links to a pdf on Hubspot, the HTML looks like this:

`<a class="hs-button " href="https://39834791.fs1.hubspotusercontent-na1.net/hubfs/39834791/Application%20Rationalization.pdf" id="hs-button_widget_1686407295591" target="_blank" rel="noopener ">
  Download our one-pager for more information
</a>`

the output from the scape command looks like this for that page:
{
"html": "",
"links": [],
"url": "https://www.theconsortium.cloud/application-consulting-services-page"
},

Is there a way, programmatically or via the CLI, to have a spider detect all of the links on a page? Or is that post-processing that needs to happen, whereby I would need to parse each page to find the links?

**Comment by j-mendez** [comment]
Hi,the full_resources feature is also required to extract assets like pdfs.

**Comment by apsaltis** [comment]
Hi @j-mendez ,
I was unaware of the full_reources feature; after installing the cli with it, I can see that all of the images and js files are found; however, the pdf links are not extracted. Perhaps I'm missing something on the correct arguments to the CLI; my intent is to ultimately use it from my Rust app, but I'm trying to get the settings correct via the CLI. 

Thanks for your help.

**Comment by apsaltis** [comment]
Noticed the comment

[`full_resources`: Enables gathering all content that relates to the domain like css,jss, and etc.](https://github.com/spider-rs/spider/blob/main/spider/src/lib.rs#L54C7-L54C104) 

Is my understanding correct that if I have a page with a link to a resource on a different domain, in my case a pdf on a page that is hosted on a different domain, then it will be ignored?

**Comment by j-mendez** [comment]
> Noticed the comment
> 
> [`full_resources`: Enables gathering all content that relates to the domain like css,jss, and etc.](https://github.com/spider-rs/spider/blob/main/spider/src/lib.rs#L54C7-L54C104)
> 
> Is my understanding correct that if I have a page with a link to a resource on a different domain, in my case a pdf on a page that is hosted on a different domain, then it will be ignored?

It should be part of the list, will push up a change shortly. Thanks for the issue.

**Comment by j-mendez** [comment]
fixed in `v1.80.79`

**Comment by apsaltis** [comment]
Hi @j-mendez -- I updated my spider-cli to v1.80.79 and still the url with the pdf never is output in the crawl. The command I'm using is:
`spider -t -v --url https://www.theconsortium.cloud/  --depth 10 -s -E *  crawl`

Not sure if this is related, but I do see the following warning.

`WARN  fast_html5ever::tree_builder] foster parenting not implemented`

I will try and spend time tomorrow debugging this as well. Thanks in advance for your help and quick response

**Comment by j-mendez** [comment]
Thanks again @apsaltis for the issue and the patience. It should be fixed in `v1.80.81`:

Use the command ` spider -t -v --url https://www.theconsortium.cloud/ --limit 1 -E "https://39834791.fs1.hubspotusercontent-na1.net" crawl` You can limit the crawl easier now with `--limit`. Using the `*` for external domains could process a lot of content.

![PDF captured from the cli using spider@v1.80.81 showing pin pointing external files for extraction](https://github.com/spider-rs/spider/assets/8095978/8e1d5fcc-1a76-4f78-8b83-0bd433940dc1)

**Comment by apsaltis** [comment]
Thank you @j-mendez! Works like a charm.
