### ISSUE TITLE
Support ignoring SSL errors

### ISSUE THREAD

**Issue by superkelvint** [spider-rs/spider#162]
Hi, is it possible to support disabling SSL verification?

**Comment by superkelvint** [comment]
@j-mendez Thank you! Would it be possible to add a cli switch to spider_cli as well please?

**Comment by j-mendez** [comment]
> > @j-mendez Thank you! Would it be possible to add a cli switch to spider_cli as well please?
> 
> good catch, doing it now, it will be out in `v1.80.85` shortly.

released - use the arg `accept_invalid_certs`. Thanks again!
