### ISSUE TITLE
Is it possible to  dynamicall add links to crawl?

### ISSUE THREAD

**Issue by oiwn** [spider-rs/spider#170]
Hello and first off, thank you for developing this fantastic software!

I am currently working on a project that involves crawling pages with dynamically generated content. To navigate through these pages, I've managed to generate direct links to the content I'm interested in. However, I've encountered a limitation when trying to integrate these links into the crawler.

The issue arises with the website.on_link_find_callback function. From my understanding, this callback is designed to process and return only one link at a time. My use case requires the ability to add multiple dynamically generated links into the crawler's queue for processing.

Is it possible?

I see there is `extra_links` but it's private.

**Comment by j-mendez** [comment]
Hi @oiwn yes this can be done in `v1.84.11`.

Use `website.set_extra_links` -> `website.persist_links` -> `website.crawl`. This will continue with the new items and avoid re-crawling the pages already visited.

**Comment by oiwn** [comment]
No way to add them in process inside `on_link_find_callback` ?

**Comment by j-mendez** [comment]
> No way to add them in process inside `on_link_find_callback` ?

No, `on_link_find_callback` is more for mutating the link and changing it to something else.

**Comment by oiwn** [comment]
Hm yea, i tried. So as far as i understand architecture  links can be processed and stored into database only at the final stage iterating through `website.get_links()` Since `on_link_find_callback` is a function pointer i can't capture any outside value and therefore unable to store urls into database inside the callback. 

But what could be strategy is there are millions of pages, and i do not want to wait while whole site will be crawled?

At first i supposed to crawl site by certain rules/patterns storing some links into redis queue, from which my small tasks framework will load them and process.

**Comment by j-mendez** [comment]
@oiwn we need to use channels for this, working on it now since this is a valid case.

**Comment by j-mendez** [comment]
This can now be done in `v1.85.0` check out the queue example folder.
