### ISSUE TITLE
Support COOKIE during the crawl [ENHANCEMENT]

### ISSUE THREAD

**Issue by Zabrane** [spider-rs/spider#186]
Hi @j-mendez 

I'm using different tools (NodeJS, Go) to preload my blog website.
They are all slow and none compares to `spider` in term of speed.

However, one thing is still missing to `spider`. The ability to support `cookie` HTTP header during the crawl.
Is there any plan for this?

Thanks

**Comment by j-mendez** [comment]
> Hi @j-mendez
> 
> I'm using different tools (NodeJS, Go) to preload my blog website. They are all slow and none compares to `spider` in term of speed.
> 
> However, one thing is still missing to `spider`. The ability to support `cookie` HTTP header during the crawl. Is there any plan for this?
> 
> Thanks

Hi, setting the cookie can be done using configuration option `cookie_str` or `website.with_cookies`.

**Comment by Zabrane** [comment]
@j-mendez This wasn't my point. A cookie is send by the server to the client (spider).
The cookie is then sent back to the server by the client (spider) every time a request is made.

Is this already implemented?

**Comment by j-mendez** [comment]
> @j-mendez This wasn't my point. A cookie is send by the server to the client (spider).
> 
> The cookie is then sent back to the server by the client (spider) every time a request is made.
> 
> 
> 
> Is this already implemented?
> 
> 

Yes this is handled by the "cookies" feature flag by default.

**Comment by Zabrane** [comment]
> Yes this is handled by the "cookies" feature flag by default.

@j-mendez  So it's by default. No need to enable anything. Very good. Please let me know when the `--depth` option is fixed so I can test it extensively.
