### ISSUE TITLE
build.rs "wget" install in benches doesn't work on non-debian distros

### ISSUE THREAD

**Issue by soulwa** [spider-rs/spider#191]
`benches/build.rs` contains a conditional command to install `wget` on linux but it assumes `apt-get` exists on the system, which isn't true on non-debian based distros. it might make sense to get rid of this line and just assume wget is installed (like the other commands which are run), since it does look like [`ubuntu-latest` has wget installed already](https://github.com/actions/runner-images/blob/0176ca6d78e6bb771cab14b76f92277fdb030908/images/ubuntu/Ubuntu2204-Readme.md?plain=1#L382), so it wouldn't break your github actions workflow. alternatively it might make sense to do something like what [`os_type`](https://github.com/schultyy/os_type) does in terms of determining the distro and appropriate package manager if this functionality is still valuable. 

for context, I tried to run this bench on arch and had to comment out these lines, since I had wget installed but obviously not apt-get

**Comment by j-mendez** [comment]
> `benches/build.rs` contains a conditional command to install `wget` on linux but it assumes `apt-get` exists on the system, which isn't true on non-debian based distros. it might make sense to get rid of this line and just assume wget is installed (like the other commands which are run), since it does look like [`ubuntu-latest` has wget installed already](https://github.com/actions/runner-images/blob/0176ca6d78e6bb771cab14b76f92277fdb030908/images/ubuntu/Ubuntu2204-Readme.md?plain=1#L382), so it wouldn't break your github actions workflow. alternatively it might make sense to do something like what [`os_type`](https://github.com/schultyy/os_type) does in terms of determining the distro and appropriate package manager if this functionality is still valuable.
> 
> for context, I tried to run this bench on arch and had to comment out these lines, since I had wget installed but obviously not apt-get

Hi thanks for the issue, feel free to push a change for this. Will try to get to it soon otherwise.
