### ISSUE TITLE
Retrieve response cookies

### ISSUE THREAD

**Issue by viktorholk** [spider-rs/spider#202]
It seems that enabling the feature: `cookies` only allows to configure the request cookies with the `cookie_str` field in the Configuration struct.

Like the `headers` feature to get the response headers i would also like to get the response cookies.

I expect that it is possible through the `chromiumoxide::Page` struct but it is a private field in the `Page`

````
pub struct Page {
    ....
    #[cfg(feature = "chrome")]
    /// Page object for chrome. The page may be closed when accessing it on another thread from concurrency.
    chrome_page: Option<chromiumoxide::Page>,
    ....
}
````
[get_cookies method](https://docs.rs/chromiumoxide/latest/chromiumoxide/page/struct.Page.html#method.get_cookies)

Thanks!

**Comment by j-mendez** [comment]
`v2.0.2` you can use `get_chrome_page` to get access to `chrome_page` now.
