### ISSUE TITLE
Memory leak caused by hashbrown

### ISSUE THREAD

**Issue by DimitriTimoz** [spider-rs/spider#207]
I have a segfault randomly with the following code, I ran it with valgrind and I got this memory leak. 

`rustc 1.80.1 (3f5fd8dd4 2024-08-06) Ubuntu`

## Code
```rust
extern crate spider;
extern crate env_logger;

use std::hash::{DefaultHasher, Hash, Hasher};

use newspaper::{Newspaper, NewspaperModel, Paper};
use spider::website::Website;
use spider::tokio;
use env_logger::Env;

use meilisearch_sdk::client::*;
  
pub mod newspaper;

async fn indexing(papers: &[Paper]) {
    println!("Indexing {} papers", papers.len());
    let client = Client::new("http://localhost:7700", Some("a")).unwrap();

    let res = client.index("papers").add_documents(papers, Some("hash_url")).await;
    match res {
        Ok(_) => println!("Indexing done"),
        Err(e) => println!("Error: {}", e),
    }
}

#[tokio::main]
async fn main() {
    let env = Env::default()
    .filter_or("RUST_LOG", "error")
    .write_style_or("RUST_LOG_STYLE", "always");
    

    let file = std::fs::File::open("newspapers.json").unwrap();
    let newspapers: Vec<NewspaperModel> = serde_json::from_reader(file).unwrap();

    let newspapers = newspapers.iter().map(|newspaper| Newspaper::from(newspaper.clone())).collect::<Vec<_>>();
    let mut hasher: DefaultHasher = DefaultHasher::new();
    // TODO: Use a thread pool to scrape multiple websites concurrently
    for paper in newspapers {
       let mut website = Website::new(paper.get_url().as_str());
        website.with_limit(100);
        println!("Scraping {}", paper.get_title());
        website.scrape().await;
        println!("Scraping done");
        let mut papers = Vec::new();
        if let Some(pages) = website.get_pages() {
            println!("Scraping pages");
            for page in pages.as_ref() {
                let html = page.get_html();

                let document = scraper::Html::parse_document(&html);
                for selector in paper.get_selectors() {
                    let texts = document.select(selector).flat_map(|el| el.text()).collect::<Vec<_>>();
                    if texts.is_empty() {
                        continue;
                    }
                    page.get_url().hash(&mut hasher);
                    papers.push(Paper {
                        title: page.get_url().to_string(),
                        url: page.get_url().to_string(),
                        content: texts.join(" "),
                        hash_url: hasher.finish()
                    });
                    break;    
                }

                if papers.len() >= 500 {
                    indexing(papers.as_slice()).await;
                    papers.clear();
                }
            }
        }
        if papers.is_empty() {
            continue;
        }
        indexing(papers.as_slice()).await;
    }
}
```
## Valgrind
```
Scraping done
Scraping pages
Indexing 14 papers
Indexing done
Error leaked 816 B in 1 block
        Info at malloc
             at alloc::alloc::alloc (alloc.rs:100)
             at alloc_impl (global.rs:35)
             at allocate (global.rs:100)
             at hashbrown::raw::inner::alloc::inner::do_alloc (alloc.rs:36)
             at hashbrown::raw::inner::RawTableInner::new_uninitialized (mod.rs:1750)
             at hashbrown::raw::inner::RawTableInner::fallible_with_capacity (mod.rs:1788)
             at hashbrown::raw::inner::RawTableInner::with_capacity (mod.rs:1815)
             at hashbrown::raw::inner::RawTable<T,A>::with_capacity_in (mod.rs:901)
             at hashbrown::raw::inner::RawTable<T>::with_capacity (mod.rs:836)
             at hashbrown::map::HashMap<K,V,S>::with_capacity_and_hasher (map.rs:505)
             at hashbrown::map::HashMap<K,V>::with_capacity (map.rs:324)
             at hashbrown::set::HashSet<T>::with_capacity (set.rs:190)
             at __static_ref_initialize (page.rs:68)
             at core::ops::function::FnOnce::call_once (function.rs:250)
     Summary Leaked 816 B total
```

## Cargo tree
```
crawler v0.1.0 (/home/dimitri/Development/fact-cheker/crawler)
├── meilisearch-sdk v0.27.1
│   ├── reqwest v0.12.7
│   │   ├── h2 v0.4.6
│   │   │   ├── indexmap v2.4.0
│   │   │   │   └── hashbrown v0.14.5
├── spider v2.1.2
│   ├── hashbrown v0.14.5 (*)
```

**Comment by j-mendez** [comment]
> I have a segfault randomly with the following code, I ran it with valgrind and I got this memory leak. 
> 
> 
> 
> `rustc 1.80.1 (3f5fd8dd4 2024-08-06) Ubuntu`
> 
> 
> 
> ## Code
> 
> ```rust
> 
> extern crate spider;
> 
> extern crate env_logger;
> 
> 
> 
> use std::hash::{DefaultHasher, Hash, Hasher};
> 
> 
> 
> use newspaper::{Newspaper, NewspaperModel, Paper};
> 
> use spider::website::Website;
> 
> use spider::tokio;
> 
> use env_logger::Env;
> 
> 
> 
> use meilisearch_sdk::client::*;
> 
>   
> 
> pub mod newspaper;
> 
> 
> 
> async fn indexing(papers: &[Paper]) {
> 
>     println!("Indexing {} papers", papers.len());
> 
>     let client = Client::new("http://localhost:7700", Some("a")).unwrap();
> 
> 
> 
>     let res = client.index("papers").add_documents(papers, Some("hash_url")).await;
> 
>     match res {
> 
>         Ok(_) => println!("Indexing done"),
> 
>         Err(e) => println!("Error: {}", e),
> 
>     }
> 
> }
> 
> 
> 
> #[tokio::main]
> 
> async fn main() {
> 
>     let env = Env::default()
> 
>     .filter_or("RUST_LOG", "error")
> 
>     .write_style_or("RUST_LOG_STYLE", "always");
> 
>     
> 
> 
> 
>     let file = std::fs::File::open("newspapers.json").unwrap();
> 
>     let newspapers: Vec<NewspaperModel> = serde_json::from_reader(file).unwrap();
> 
> 
> 
>     let newspapers = newspapers.iter().map(|newspaper| Newspaper::from(newspaper.clone())).collect::<Vec<_>>();
> 
>     let mut hasher: DefaultHasher = DefaultHasher::new();
> 
>     // TODO: Use a thread pool to scrape multiple websites concurrently
> 
>     for paper in newspapers {
> 
>        let mut website = Website::new(paper.get_url().as_str());
> 
>         website.with_limit(100);
> 
>         println!("Scraping {}", paper.get_title());
> 
>         website.scrape().await;
> 
>         println!("Scraping done");
> 
>         let mut papers = Vec::new();
> 
>         if let Some(pages) = website.get_pages() {
> 
>             println!("Scraping pages");
> 
>             for page in pages.as_ref() {
> 
>                 let html = page.get_html();
> 
> 
> 
>                 let document = scraper::Html::parse_document(&html);
> 
>                 for selector in paper.get_selectors() {
> 
>                     let texts = document.select(selector).flat_map(|el| el.text()).collect::<Vec<_>>();
> 
>                     if texts.is_empty() {
> 
>                         continue;
> 
>                     }
> 
>                     page.get_url().hash(&mut hasher);
> 
>                     papers.push(Paper {
> 
>                         title: page.get_url().to_string(),
> 
>                         url: page.get_url().to_string(),
> 
>                         content: texts.join(" "),
> 
>                         hash_url: hasher.finish()
> 
>                     });
> 
>                     break;    
> 
>                 }
> 
> 
> 
>                 if papers.len() >= 500 {
> 
>                     indexing(papers.as_slice()).await;
> 
>                     papers.clear();
> 
>                 }
> 
>             }
> 
>         }
> 
>         if papers.is_empty() {
> 
>             continue;
> 
>         }
> 
>         indexing(papers.as_slice()).await;
> 
>     }
> 
> }
> 
> ```
> 
> ## Valgrind
> 
> ```
> 
> Scraping done
> 
> Scraping pages
> 
> Indexing 14 papers
> 
> Indexing done
> 
> Error leaked 816 B in 1 block
> 
>         Info at malloc
> 
>              at alloc::alloc::alloc (alloc.rs:100)
> 
>              at alloc_impl (global.rs:35)
> 
>              at allocate (global.rs:100)
> 
>              at hashbrown::raw::inner::alloc::inner::do_alloc (alloc.rs:36)
> 
>              at hashbrown::raw::inner::RawTableInner::new_uninitialized (mod.rs:1750)
> 
>              at hashbrown::raw::inner::RawTableInner::fallible_with_capacity (mod.rs:1788)
> 
>              at hashbrown::raw::inner::RawTableInner::with_capacity (mod.rs:1815)
> 
>              at hashbrown::raw::inner::RawTable<T,A>::with_capacity_in (mod.rs:901)
> 
>              at hashbrown::raw::inner::RawTable<T>::with_capacity (mod.rs:836)
> 
>              at hashbrown::map::HashMap<K,V,S>::with_capacity_and_hasher (map.rs:505)
> 
>              at hashbrown::map::HashMap<K,V>::with_capacity (map.rs:324)
> 
>              at hashbrown::set::HashSet<T>::with_capacity (set.rs:190)
> 
>              at __static_ref_initialize (page.rs:68)
> 
>              at core::ops::function::FnOnce::call_once (function.rs:250)
> 
>      Summary Leaked 816 B total
> 
> ```
> 
> 
> 
> ## Cargo tree
> 
> ```
> 
> crawler v0.1.0 (/home/dimitri/Development/fact-cheker/crawler)
> 
> ├── meilisearch-sdk v0.27.1
> 
> │   ├── reqwest v0.12.7
> 
> │   │   ├── h2 v0.4.6
> 
> │   │   │   ├── indexmap v2.4.0
> 
> │   │   │   │   └── hashbrown v0.14.5
> 
> ├── spider v2.1.2
> 
> │   ├── hashbrown v0.14.5 (*)
> 
> ```
> 
> 

Hi thanks for the issue. Did you put an issue in the hashbrown project? Also if you can put your OS so we can better triage if not.

**Comment by DimitriTimoz** [comment]
> Hi thanks for the issue. Did you put an issue in the hashbrown project? Also if you can put your OS so we can better triage if not.

Hi, yes, I have.  
I'm using `Ubuntu 24.04 LTS.` After some tests, the error doesn't occur on macOS with M1. The reason for the previous leak could be explained by the lazy static that intentionally leaks.

I've been running my program for 3 hours now with Valgrind. I don't know why, but it's really slow, and I still haven't encountered a segfault.


Here are my logs, I don't know why but this time the error occurs at a different step :
```
cargo run --release
    Finished `release` profile [optimized] target(s) in 0.12s
     Running `target/release/crawler`
Scraping Le Monde
Scraping done
Scraping pages
Segmentation fault (core dumped)
```
I think that it isn't impossible that another crate cause the segfault but according to my logs sometimes it's caused by `.scrape()`, others `Html::parse_document` (not this one since a cargo update).
So I will start to investigate my PC.
Morever if it's caused by `scraper` it's realy strange because when I run it with the html page which has been run just before the segfault the segfault doesn't occur again.

**Comment by DimitriTimoz** [comment]
> I've been running my program for 3 hours now with Valgrind. I don't know why, but it's really slow, and I still haven't encountered a segfault.

So I started it again without valgrind in release and this time again it's caused by the `.scrape()` method. But it's strange, in release the segfault are realy more frequents.

**Comment by DimitriTimoz** [comment]
So I commented all the code consering `meilisearch`  and `scraper` . The segfault occurs again. 
Here are a part of the logs :
```
Getting page:
https://www.lemonde.fr/archives-du-monde/
Parsing page
Page done
Getting page:
https://www.lemonde.fr/sport/jo-paralympiques-2024/resultats/
Parsing page
Page done
Getting page:
https://www.lemonde.fr/crise-ukrainienne/
Parsing page
Page done
Getting page:
https://www.lemonde.fr/series-d-ete/article/2024/08/28/trump-fictions-fast-and-furious-pied-au-plancher_6297338_3451060.html
Segmentation fault (core dumped)
```
And here the related code :
``` rust
       let mut website = Website::new(paper.get_url().as_str());
        website.with_limit(10_000);
        println!("Scraping {}", paper.get_title());
        website.scrape().await;
        println!("Scraping done");
        //let mut papers = Vec::new();
        if let Some(pages) = website.get_pages() {
            println!("Scraping pages");
            for page in pages.as_ref() {
                println!("Getting page:");
                println!("{}", page.get_url());
                let html = page.get_html();
                println!("Parsing page");
            }
          println!("Page done");
   }
```

**Comment by j-mendez** [comment]
In the meantime you can switch to subscriptions and process each one  instead of waiting and holding all the data in memory. The memory for the hashmap should release on drop.

**Comment by j-mendez** [comment]
The issue is in debug builds from the UTF encoding only in non release builds:

This is the code inside the Rust default `String::from_utf8_lossy`

```rs
debug_assert_eq!(valid.len(), v.len());
```

This is now handled automatically `2.2.0` so that you can get the locales encoded correctly.

**Comment by DimitriTimoz** [comment]
I'm sorry but I still have the segfault, in release and debug. 
Here are the logs but it can happen elsewhere.
On `.scrape()`
```
...
[2024-08-29T10:42:47Z INFO  spider::utils] fetch - https://www.lemonde.fr/international/article/2023/09/08/hongkong-connait-un-niveau-record-de-precipitations-qui-entrainent-des-inondations_6188376_3210.html
[2024-08-29T10:42:47Z INFO  spider::utils] fetch - https://www.lemonde.fr/planete/article/2024/06/20/paris-2024-l-objectif-climatique-des-jeux-ne-sera-pas-tenu-en-raison-des-deplacements-en-avion-selon-un-rapport-independant_6241833_3244.html
[2024-08-29T10:42:47Z INFO  spider::utils] fetch - https://www.lemonde.fr/politique/article/2024/06/21/pouvoir-d-achat-retraites-croissance-comment-le-nouveau-front-populaire-a-compose-son-programme-pour-les-legislatives_6241927_823448.html
[2024-08-29T10:42:47Z INFO  spider::utils] fetch - https://www.lemonde.fr/portraits-de-famille/
Segmentation fault (core dumped)
```

On `.scrape()`
```
...
[2024-08-29T10:45:13Z INFO  spider::utils] fetch - https://www.lemonde.fr/resultats-legislatives-2024/tressin-59602/
[2024-08-29T10:45:13Z INFO  spider::utils] fetch - https://www.lemonde.fr/resultats-legislatives-2024/hoerdt-67205/
[2024-08-29T10:45:13Z INFO  spider::utils] fetch - https://www.lemonde.fr/en/international/article/2024/05/18/in-bulgaria-revelations-about-a-mysterious-air-disaster_6671797_4.html
double free or corruption (fasttop)
Aborted (core dumped)
```

on the `get_url()`
````
...
[2024-08-29T10:45:55Z INFO  spider::utils] fetch - https://www.lemonde.fr/sport/article/2024/08/07/athletisme-aux-jo-2024-gabriel-tual-dans-le-gotha-mondial-du-800-m_6272133_3242.html
[2024-08-29T10:45:55Z INFO  spider::utils] fetch - https://www.lemonde.fr/en/culture/article/2024/03/20/inside-zola-s-home-where-literature-and-pleasure-coexisted_6636181_30.html
[2024-08-29T10:45:55Z INFO  spider::utils] fetch - https://www.lemonde.fr/en/culture/article/2024/08/23/in-emilia-perez-jacques-audiard-tells-the-story-of-a-transgender-kingpin-in-the-world-of-mexican-cartels_6720692_30.html
Scraping done
Scraping pages
Getting page:
https://www.lemonde.fr/
double free or corruption (fasttop)
double free or corruption (fasttop)
double free or corruption (fasttop)
```

It's strange because it's not always at the same step and same memory issue. 
It doesn't happen on my mac.

**Comment by DimitriTimoz** [comment]
Everything is caused by openssl, I'm trying to disable it
