### ISSUE TITLE
It's colly not crolly

### ISSUE THREAD

**Issue by melroy89** [spider-rs/spider#214]
https://github.com/spider-rs/spider/blob/main/benches/go_crolly.rs

It's called Colly, right? Not Crolly.

Also do not forget to update: https://github.com/spider-rs/spider/blob/main/benches/BENCHMARKS.md#linux

**Comment by melroy89** [comment]
Nice! You're fast.

**Comment by j-mendez** [comment]
> Nice! You're fast.

thanks for the issue!
