### ISSUE TITLE
Publish spider CLI binaries

### ISSUE THREAD

**Issue by alexkreidler** [spider-rs/spider#217]
Publishing binaries on Github releases would save people from having to build the CLI, which can take a while especially on low-resource devices. Then they can install with [cargo-binstall](https://github.com/cargo-bins/cargo-binstall): `cargo binstall spider_cli`, or by curling the Github releases URL.

A Github action to run cargo build and publish would be pretty quick to setup and very useful. Thanks for an awesome project!

**Comment by asymmetric1947** [comment]
+1 for this, would help a lot with deployment
