### ISSUE TITLE
Add CSS exclude selectors to /crawl endpoint

### ISSUE THREAD

**Issue by mikoro** [spider-rs/spider#219]
Add possibility to exclude content on the page based on CSS selectors.

**Comment by boehlerlukas** [comment]
@mikoro we are looking for the same at the moment. Spider looks really promising for us at [Gleap](https://www.gleap.io/) - excited to see it perform in production.

**Comment by j-mendez** [comment]
released for transformations `v2.9.15`

**Comment by boehlerlukas** [comment]
Awesome, thanks a lot!

**Comment by j-mendez** [comment]
> Awesome, thanks a lot! @j-mendez is this also available through the /crawl api of https://spider.cloud/ ? We prefer the cloud over self hosting :)

No problem, yes this is now available on the cloud too.

**Comment by boehlerlukas** [comment]
@j-mendez any push into the right direction would be much appreciated as we are currently lookin for a better performing crawler than crawlee.

**Comment by j-mendez** [comment]
> @j-mendez any push into the right direction would be much appreciated as we are currently lookin for a better performing crawler than crawlee.

released in v2.10.0 - deploy will be out in 30 mins. Use `exclude_selector` to remove the elements from the markup. https://github.com/spider-rs/spider/commit/2065600f2e81c76bfb4ef7cea594c45716baeed8

**Comment by boehlerlukas** [comment]
@j-mendez awesome, this was super fast!
