### ISSUE TITLE
Crawling tooks forever, does not end

### ISSUE THREAD

**Issue by Arputikos** [spider-rs/spider#223]
I am trying to crawl a full website that contains a few thousants of pages. Small websites worked, but when i try specific one: www.powerrubber.com, then it just stucks in a forever loop, crawling and crawling. Turned on debug logs and it prints some links but also lots of such warnings:
-  WARN  fast_html5ever::tree_builder] foster parenting not implemented
- spider::utils] URL Parse Error:  - invalid domain character
- spider::utils] URL Parse Error:  - empty host
and it just goes and goes for 30...60... minutes and doesn't stop.
Having in mind that spider is THAT fast and scrapes thousand pages in no more than a few seconds, it's weird.
Played with configuration.depth but it doesn't work as I would expect (I would assume that setting this to 4-5 would crawl almost everything (all the products)).

Here is the code:
```
use std::path::Path;
use spider::url::Url;
use spider::website::Website;
use env_logger::Env;

#[tokio::main]
async fn main() {
    //enable logs
    let env = Env::default()
    .filter_or("RUST_LOG", "info")
    .write_style_or("RUST_LOG_STYLE", "always");
    env_logger::init_from_env(env);

    //crawl the website
    let mut website = Website::new("https://example.com");
    website.configuration.respect_robots_txt = true;

    website.crawl().await;

    let links = website.get_links();
    for link in links.iter() {
        println!("- {:?}", link.as_ref());
    }
    println!("Links count {}", links.len());
}
```

What to do to crawl this website and all the products in a finished time?

**Comment by j-mendez** [comment]
I would try using the `subscribe` feature. This website has millions of pages possibly, theres not any code that will make the crawler stuck in a loop when you are not using the `subcribe_guard` which waits for you to finish the subscriptions processing.
