### ISSUE TITLE
tcp keepalive issues

### ISSUE THREAD

**Issue by ilpanich** [spider-rs/spider#224]
Hi!
I have this kind of issues:
`{"v":0,"name":"---","message":"tcp set_keepalive error: Invalid argument (os error 22)","severity":"WARNING","timestampSeconds":1730129780,"timestampNanos":584648375,"logging.googleapis.com/sourceLocation":{"function":"hyper_util::client::legacy::connect::http","line":719,"file":"/usr/local/cargo.cache/1.82.0-slim-bookworm/registry/src/index.crates.io-6f17d22bba15001f/hyper-util-0.1.9/src/client/legacy/connect/http.rs"}}`

When I run the spider to crawl from an HTTP (not HTTPS) endpoint.

Tried with v2.10.26.

I don't think it is an issue, I believe I have misconfigured something. Can you please help me?

Thank you

**Comment by j-mendez** [comment]
Hi, are you adjusting the tcp keep alive option in reqwest?

**Comment by j-mendez** [comment]
This issue belongs in https://github.com/hyperium/hyper/issues?page=2&q=TCP+keep+alive

**Comment by ilpanich** [comment]
Sorry @j-mendez, to which issue on the link (hyper issues page 2) do you refer?
Honestly I can't figure it out...
