### ISSUE TITLE
Access to reqwest internal structures ?

### ISSUE THREAD

**Issue by rgrunbla** [spider-rs/spider#226]
Hi,

Is it possible to have access to reqwest internal structures, e.g. [Response](https://docs.rs/reqwest/latest/reqwest/struct.Response.html), during a crawl / scrape made by spider ? My main use case would be having access to `remote_addr`, but I expect having such an access could be interesting for more fields.

Thanks !

**Comment by j-mendez** [comment]
Hi, you can get the `remote_addr` now in `v2.21.5`. We cannot store the response in the page currently. Thank you
