### ISSUE TITLE
Delay and with_delay totally breaks crawl

### ISSUE THREAD

**Issue by Revertron** [spider-rs/spider#232]
It seems that the `website.crawl().await` is not working at all when using delays like 1000 (one second).
Maybe this is the cause of #225 also.

And the culprit of this is the `select!()` on this line: https://github.com/spider-rs/spider/blob/main/spider/src/website.rs#L2227.

The stream is throttled, so the select!() is always selecting other tasks, and never fetches any links.

**Comment by j-mendez** [comment]
Hi, what version of spider are you using? The select will perform both of the tasks at the same time concurrently independent of each other. There was a bug in an older version. Make sure to use `v2.13.76` and above (currently `v2.13.79`).

**Comment by j-mendez** [comment]
The issue you were facing most likely was from the example redirecting to example.com. Updated the default target url to fix this.

**Comment by Revertron** [comment]
I've tried the latest version, from master.
And I didn't use urls in examples.

Why did you close the issue?

From the docs of tokio:

The tokio::select! macro allows waiting on multiple async computations and returns when a **single** computation completes.

Did you try big delay, like 1000?

**Comment by j-mendez** [comment]
Yes, tested this with a delay of one second. The select is cancel safe because it uses a join_next from a JoinSet.

**Comment by j-mendez** [comment]
Ran it again to make sure. Going to see what happened in the morning. Thanks for the issue.
https://github.com/user-attachments/assets/8f3eb9ce-2409-4967-a0cf-0b200e0df690

**Comment by j-mendez** [comment]
Fixed via `2.13.80` also improved the performance reducing extra context switching. Thank you!

**Comment by Revertron** [comment]
Okay, now it seems working. Thank you!

**Comment by j-mendez** [comment]
> Okay, now it seems working. Thank you!

update the crate to `v2.13.82` there was an overlook on the throttling.
