### ISSUE TITLE
Starting crawl from long url always loads only one page

### ISSUE THREAD

**Issue by Revertron** [spider-rs/spider#233]
If I want to crawl some website for new pages I would want to start from some particular page, not the root. Like `https://habr.com/en/feed/` for example. But spider always loads only that page and doesn't go further by links on that page.

**How can I circumvent this?**

And the same behavior is with addition of trailing slash: `https://habr.com` is starting crawling, but `https://habr.com/` is loading only that page and then stops.

**Comment by j-mendez** [comment]
fixed in latest release - thank you
