### ISSUE TITLE
Budget feature doesn't exist?

### ISSUE THREAD

**Issue by EHPS-Oliver** [spider-rs/spider#236]
The docs for methods such as `.with_limit()` say `    /// Set a crawl page limit. If the value is 0 there is no limit. This does nothing without the feat flag `budget` enabled.` However when I put the budget flag in my `Cargo.toml` I get the following message:
> the package `surreal_spider` depends on `spider`, with features: `budget` but `spider` does not have these features.

**Comment by j-mendez** [comment]
@EHPS-Oliver thanks for the issue fixed `2.21.18`
