### ISSUE TITLE
Possible incomplete comment

### ISSUE THREAD

**Issue by YichiZhang0613** [spider-rs/spider#237]
In spider-main/spider_chrome/src/error.rs, the comment indicates the code will panic if now > deadline, while it is not checked in fn new. Instead, some logical processing is performed where the new is called, rather than panic. 
```rust
impl DeadlineExceeded {
    /// Creates a new instance
    ///
    /// panics if `now > deadline`
    pub fn new(now: Instant, deadline: Instant) -> Self {
        // assert!(now > deadline);
        Self { deadline, now }
    }
}
```

**Comment by j-mendez** [comment]
we use this in the command chain. The code will never panic, it is used for a timer to prevent hanging ws messages.
