### ISSUE TITLE
Add Documentation about new features of the spider

### ISSUE THREAD

**Issue by mgifford** [spider-rs/spider#81]
Looking at https://github.com/spider-rs/spider/blob/main/spider_cli/README.md

I think this got brought into the code https://github.com/spider-rs/spider/issues/79

Or it got bumped off the todo list.  Either is fine, but would be nice if it was built if folks knew how to use it.

**Comment by j-mendez** [comment]
Hi @mgifford , I put a message that the spider is set for being an indexer. You can add something like this with a fork easy. We have the features documented on the README and on crates.io.

**Comment by mgifford** [comment]
No worries.  I just read "[j-mendez](https://github.com/j-mendez) closed this as [completed](https://github.com/spider-rs/spider/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [1 hour ago](https://github.com/spider-rs/spider/issues/79#event-8355999563)" as "I built it, done!" vs "this is out of scope, sorry". 

I also like the idea of a fork..  Lots of good reasons to move in that direction. Think it helps for the spider-rs project's viability to show folks experimenting with it.

**Comment by j-mendez** [comment]
@mgifford Here is a bit more direction on the missing links, you can adjust this line here and use the [scraper](https://docs.rs/scraper/latest/scraper/) to parse out the link info https://github.com/spider-rs/spider/blob/main/spider/src/page.rs#L186.

testcase: https://github.com/spider-rs/spider/blob/main/spider/src/page.rs#L232.

I hope this helps!
